### ISSUE TITLE
Does not parse area code for US numbers

### ISSUE THREAD

**Issue by matthewkimber** [GlobalPhone/GlobalPhone#16]
I found this curious that when parsing US phone numbers the area code always returns `null`. However, when parsing numbers in Europe the area code is populated. Is this a bug or by design?

**Comment by wallymathieu** [comment]
Looks like the data is missing from the json file. Does [libphonenumber-csharp](https://github.com/erezak/libphonenumber-csharp) have the same issue?

**Comment by matthewkimber** [comment]
I will check it out.
