### ISSUE TITLE
DatabaseGenerator is concatenating leadingDigits collection from XML source into one pattern string

### ISSUE THREAD

**Issue by samcic** [GlobalPhone/GlobalPhone#17]
Perhaps I can start with an example: the GB mobile phone number 07400 123456. If we put that into the libphonenumber online tool (https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html), then it returns the formatted national string "07400 123456" (as expected).

If I try to parse that number using GlobalPhone.Parse("07400 123456", "GB"), it returns "074 0012 3456" as the formatted national string, which looks incorrect (note the spacing).

I had a bit of a debug and it seems that the correct format for displaying this number is not being chosen. In the source XML from libphonenumber, the corresponding XML fragment for this case is:

        <numberFormat pattern="(7\d{3})(\d{6})">
          <leadingDigits>
            7(?:
              [1-5789]|
              62
            )
          </leadingDigits>
          <leadingDigits>
            7(?:
              [1-5789]|
              624
            )
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>

That is, there are two leadingDigits elements here. Now, if we have a look at how GlobalPhone stores the leadingDigits when it parses the database (here a slight modification of one of your unit tests):

[Test]
        public void it_can_generate_data_without_causing_an_exception() 
        {
            var generator = DatabaseGenerator.Load(new WebClient().DownloadString("https://raw.githubusercontent.com/googlei18n/libphonenumber/master/resources/PhoneNumberMetadata.xml"));
            var result = generator.RecordData().ToList();
            var countryCode44 = result[63];
            var leadingDigits = ((IDictionary[]) countryCode44["formats"])[4]["leadingDigits"];
        }

...the leadingDigits variable here has the value "7(?:[1-5789]|62)7(?:[1-5789]|624)", i.e. it seems to me that both of the XML node patterns have simply been concatenated into a big long string pattern, which doesn't seem right at all! This seems to be the problem that's causing various formatting issues in an application of ours. Are you able to confirm that this is indeed a bug, or am I missing something? If this is indeed a bug, it probably affects any case where there is more than one leadingDigits XML element, right?

**Comment by wallymathieu** [comment]
That looks indeed like a bug. Perhaps that we should add your regression test?

**Comment by wallymathieu** [comment]
Good work on finding this issue.

**Comment by samcic** [comment]
Thanks :). I'm glad to hear that my description was understandable and that we both agree it's a problem.

To help understand the impact, I did a quick XPath query of the current master PhoneNumberMetadata.xml file on GitHub, and noticed that 22 out of 253 territories have at least one number format definition with more than one leadingDigits element. That means that this bug will potentially manifest in formatting errors for other regions (AR and AU for example). The XPATH query I used to find those is //territory[availableFormats/numberFormat[count(leadingDigits)>1]]
(wrapping that in a count() gives 22 matching territories back).

If I understand correctly, GlobalPhone is only using the leadingDigits information to do formatting. That is, based on a global search for "leadingDigits" in the solution, it seems that the information is only being used in the Format class. This means that parsing should not be affected (good news).

At the moment, the leadingDigits value in the format object is being set in the CompileFormat method of the DatabaseGenerator class. It gets the value from the Pattern method , which in turn calls TextOrNull, which is where the buggy "concatenation" of text from multiple leadingDigits nodes seems to be happening.

I see a two possible ways to fix this...

1. Appreciate that there may be more than one leadingDigits node, which will probably require a change to the *.json database structure (i.e. leadingDigits would no longer just be a string value, but rather an array of strings or similar). Depending on how this is implemented this may be a breaking change (i.e. consider the case where existing users update GlobalPhone but keep an old *.json database with the old structure).
 
2. Keep the leadingDigits property as a string, but do some regex tweaking to represent all the possible formatting alternatives in the one regex. That is, a regex something like this...
(?:leadingDigitsRegex1)|(?:leadingDigitsRegex2)
...where leadingDigitsRegex1 is the regex coming from the first leadingDigits node, leadingDigitsRegex2 is the regex coming from the second leadingDigits node etc.
Seeing as the leadingDigits are only being used for matching purposes in the Format class, this seems like it would work (note that I'm no regex expert...there might be a better way to do it than the way I've described above).

Although approach #2 is perhaps simpler to implement, #1 is perhaps the less-hacky solution. I'll leave it to you guys to decide the appropriate direction. Maybe you also have other approaches that are more appropriate.

**Comment by wallymathieu** [comment]
I would prefer that we change the database structure. #1 is definitely the less hackish solution. If we do a major version change then an update to the format is more than acceptable.

**Comment by wallymathieu** [comment]
Fixing the format does not fix the bug.

**Comment by wallymathieu** [comment]
The format is fixed.
