### ISSUE TITLE
Will you support CoreCLR?

### ISSUE THREAD

**Issue by agoretsky** [GlobalPhone/GlobalPhone#18]
Hi, thank you for your work!
Are there any plans to port GlobalPhone over the the CoreCLR?

**Comment by wallymathieu** [comment]
Either by someone doing a pull request or if I need it for some project.

**Comment by wallymathieu** [comment]
https://www.nuget.org/packages/GlobalPhone/5.0.0

**Comment by agoretsky** [comment]
@wallymathieu, thank you!

**Comment by agoretsky** [comment]
@wallymathie, in project "system.xml.xpath.xmldocument": "4.0.0" it should be "System.Xml.XPath.XmlDocument" and why not 4.01 version? There is a conflict when I install your library with, for example, "Ngonzalez.HtmlAgilityPack": "2.0.0".

**Comment by agoretsky** [comment]
If I change "system.xml.xpath.xmldocument" in project.lock.json file to "System.Xml.XPath.XmlDocument" everything is ok, it is keysensitive, so please fix it

**Comment by wallymathieu** [comment]
Perhaps create a pull request with the fix?

**Comment by agoretsky** [comment]
https://github.com/GlobalPhone/GlobalPhone/pull/20
