### ISSUE TITLE
No linux support?

### ISSUE THREAD

**Issue by saviour123** [GlobalPhone/GlobalPhone#23]
How can I get this to work on dotnet on linux with vscode.
-how do i do the conversion?

**Comment by wallymathieu** [comment]
I'm afraid I don't understand? The version currently on nuget is built to function either against netstandard 1.6 or higher or .net 4.5 or higher. What doesn't work?

**Comment by wallymathieu** [comment]
On linux you would do
```
> mono ./packages/GlobalPhoneDbgen/tools/GlobalPhoneDbgen.exe > db/global_phone.json
```
However, there is currently a bug (in this lib) #22 due to a change of file format that causes this lib to fail to parse numbers. You could use an old file or go with the lib mentioned in the issue.
