### ISSUE TITLE
Remove parts of the lib in favor of libphonenumber-csharp 

### ISSUE THREAD

**Issue by wallymathieu** [GlobalPhone/GlobalPhone#26]
See https://github.com/twcclegg/libphonenumber-csharp/issues/57#issuecomment-370910150

I can imagine one deviation could be: [E.161](https://github.com/GlobalPhone/GlobalPhone/blob/master/src/GlobalPhone/E161.cs)

Since it's relatively few lines of code, it might be better to see if that could be contributed to libphonenumber.

Goals: 
- Provide wrappers to simplify access to library features in libphonenumber
- If there is no sufficient reason to keep GlobalPhone as a separate lib, deprecate it in favor of the more maintained lib

**Comment by wallymathieu** [comment]
If you want @twcclegg I could add you as a member of @GlobalPhone/owners in order for you to be able to modify these projects as well (and perhaps code review changes)?

**Comment by twcclegg** [comment]
I don't know that that's all that necessary, I can review things unoffically or submit changes if need be.
