### ISSUE TITLE
Question around assembly load From NuGet

### ISSUE THREAD

**Issue by wallymathieu** [GlobalPhone/GlobalPhone#31]
> First of all, thanks for creating this library. It's served me well, and I'm a great fan of it. But it seems your most recent package may have some problems.
I am using it in an app I'm building, using .NET Core 3.0, and getting the error below:
System.IO.FileLoadException: Could not load file or assembly 'PhoneNumbers, Version=8.10.1.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040) File name: 'PhoneNumbers, Version=8.10.1.0, Culture=neutral, PublicKeyToken=null' at GlobalPhone.Context..ctor() at GlobalPhone.GlobalPhone.get_Context() at GlobalPhone.GlobalPhone.TryParse(String str, Number& number, String territoryName)
Any help will be greatly appreciated.

**Comment by sunnyhighway** [comment]
Had the same problem.
But adding a reference to **libphonenumber-csharp** Version: 8.10.10 or greater to my project worked for me.
See: https://www.nuget.org/packages/libphonenumber-csharp/

Worthy of note is that the exception mentions: "Could not load file or assembly '**PhoneNumbers**, Version=8.10.1.0"
